INSERT INTO CUSTOMER (CUSTOMERID, COMPANY, FORENAME, SURNAME, ADDRESS) VALUES (1, "RyoUkot", "Petteri", "Kivi", "Kuja 2");
INSERT INTO DELIVERY (DELIVERYID, MAXSIZE, MAXWEIGHT, DELIVERY_DATE, DELIVERY_ADDRESS) VALUES (1, 100, 100, '2020-06-14' , "Kotikuja 13, 65200 VAASA");
INSERT INTO ORDERS (ORDERDATE, ORDERID) VALUES ('2020-04-14', 1);
INSERT INTO PRODUCT (PRODUCTID, PRODUCTNAME, PRICE, QUANTITY, SIZE, WEIGHT) VALUES (1, "Sohva", 900, 1, 80, 1);
INSERT INTO ORDERPRODUCT (ORDERPRODUCT, PRODUCTCOUNT) VALUES (325325, 2);
INSERT INTO CUSTOMER (CUSTOMERID, COMPANY, FORENAME, SURNAME, ADDRESS) VALUES (2, "RyoUkot", "Pete", "Oja", "Kuja 3");
INSERT INTO CUSTOMER (CUSTOMERID, COMPANY, FORENAME, SURNAME, ADDRESS) VALUES (3, "Ryoäijät", "Topi", "Saha", "Tie 15");
INSERT INTO PRODUCT (PRODUCTID, PRODUCTNAME, PRICE, QUANTITY, SIZE, WEIGHT) VALUES (2, "Sänky", 800, 13, 90, 2);