CREATE TABLE STORAGE ( 
    STORAGELOCATION INT NOT NULL PRIMARY KEY,
    CAPACITY INT NOT NULL, 
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT (PRODUCTID));

CREATE TABLE ORDERS ( 
    ORDERDATE DATE NOT NULL,
    ORDERID INT NOT NULL PRIMARY KEY, 
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT (PRODUCTID),
    FOREIGN KEY (DELIVERYID) REFERENCES DELIVERY (DELIVERYID),
    FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER (CUSTOMERID));

CREATE TABLE DELIVERY ( 
    MAXWEIGHT INT NOT NULL,
    MAXSIZE INT NOT NULL, 
    DELIVERY_DATE DATE NOT NULL, 
    DELIVERY_ADDRESS VARCHAR(100) NOT NULL,
    DELIVERYID INT NOT NULL PRIMARY KEY, 
    FOREIGN KEY (ORDERID) REFERENCES ORDERS (ORDERID));

CREATE TABLE PRODUCT ( 
    PRODUCTNAME VARCHAR(100) NOT NULL,
    PRODUCTID INT NOT NULL PRIMARY KEY, 
    PRICE INT NOT NULL, 
    QUANTITY INT NOT NULL, 
    SIZE INT NOT NULL,
    WEIGHT INT NOT NULL,
    FOREIGN KEY (ORDERID) REFERENCES ORDERS (ORDERID),
    FOREIGN KEY (STORAGELOCATION) REFERENCES STORAGE (STORAGELOCATION));

CREATE TABLE CUSTOMER ( 
    CUSTOMERID INT NOT NULL PRIMARY KEY,
    COMPANY VARCHAR(100) NOT NULL,
    FORENAME VARCHAR(100), 
    SURNAME VARCHAR(100), 
    ADDRESS VARCHAR(100) NOT NULL, 
    FOREIGN KEY (ORDERID) REFERENCES ORDERS (ORDERID),
    FOREIGN KEY (DELIVERYID) REFERENCES DELIVERY (DELIVERYID));



-- sijoitetaan customer tauluun-->
-- INSTERT INTO CUSTOMER (CUSTOMERID, COMPANY, FORENAME) VALUES (12345, 6789, "VILLEPETTERI"); 
-- avataan customer näkyviin
-- SELECT * FROM CUSTOMER;
-- poistetaan customer taulu
-- DROP TABLE CUSTOMER;
