
--subquery
-- Find product in certain storagelocation
SELECT * FROM PRODUCT WHERE STORAGELOCATION=(SELECT STORAGELOCATION FROM STORAGES WHERE STORAGELOCATION=2);
-- Find which delivery belongs to which orders
SELECT * FROM DELIVERY WHERE DELIVERYID=(SELECT DELIVERYID FROM ORDERS WHERE DELIVERYID = 2);
-- Find customer which customerid matches deliveryadress
SELECT * FROM CUSTOMER WHERE CUSTOMERID=(SELECT DELIVERYID FROM DELIVERY WHERE DELIVERY_ADDRESS = 'Kotikuja 13, 65200 VAASA');
-- Find product which productname matches storages table productname
SELECT * FROM PRODUCT WHERE PRODUCTNAME=(SELECT PRODUCTNAME FROM STORAGES WHERE PRODUCTNAME = 'Sohva');

SELECT * FROM PRODUCT WHERE PRICE BETWEEN 250 AND 800;
SELECT * FROM ORDERS WHERE ORDERDATE LIKE '2020%';
SELECT * FROM CUSTOMER WHERE FORENAME LIKE 'P_t%';

--Saadaan näkyviin tuotteet ja niiden varastopaikat
SELECT * FROM STORAGES LEFT JOIN PRODUCT ON STORAGES.STORAGELOCATION = PRODUCT.STORAGELOCATION;
--Nähdään asiakkaan osoite, yritysnimi ja milloin tuote heille toimitetaan.
SELECT CUSTOMER.COMPANY, CUSTOMER.ADDRESS, DELIVERY.DELIVERY_DATE FROM CUSTOMER INNER JOIN DELIVERY ON CUSTOMER.CUSTOMERID = DELIVERY.CUSTOMERID;
--Saadaan näkyviin Etu- ja Sukunimi sekä tilauspvm.
SELECT CUSTOMER.FORENAME, CUSTOMER.SURNAME, ORDERS.ORDERDATE FROM CUSTOMER INNER JOIN ORDERS ON CUSTOMER.CUSTOMERID = ORDERS.CUSTOMERID;
--näyttää ostokorin tilaukselle 1
SELECT ORDERS.ORDERID, ORDERS.CUSTOMERID, ORDERPRODUCT.PRODUCTID, ORDERPRODUCT.PRODUCTCOUNT FROM ORDERS INNER JOIN ORDERPRODUCT ON ORDERS.ORDERID = ORDERPRODUCT.ORDERID WHERE ORDERS.ORDERID = 1;