
--subquery
SELECT * FROM PRODUCT WHERE STORAGELOCATION=(SELECT STORAGELOCATION FROM STORAGES WHERE STORAGELOCATION=2);
SELECT * FROM DELIVERY WHERE DELIVERYID=(SELECT DELIVERYID FROM DELIVERY WHERE DELIVERYID = 2 AND CUSTOMERID = 2);
SELECT * FROM CUSTOMER WHERE CUSTOMERID=(SELECT DELIVERYID FROM DELIVERY WHERE DELIVERY_ADDRESS = 'Kotikuja 13, 65200 VAASA');
SELECT * FROM PRODUCT WHERE PRODUCTNAME=(SELECT PRODUCTNAME FROM STORAGES WHERE PRODUCTNAME = 'Sohva');

SELECT * FROM PRODUCT WHERE PRICE BETWEEN 250 AND 800;
SELECT * FROM ORDERS WHERE ORDERDATE LIKE '2020%';
SELECT * FROM CUSTOMER WHERE FORENAME LIKE 'P_t%';

SELECT * FROM STORAGES LEFT JOIN PRODUCT ON STORAGES.STORAGELOCATION = PRODUCT.STORAGELOCATION;
SELECT CUSTOMER.COMPANY, CUSTOMER.ADDRESS, DELIVERY.DELIVERY_DATE FROM CUSTOMER INNER JOIN DELIVERY ON CUSTOMER.CUSTOMERID = DELIVERY.CUSTOMERID;
SELECT CUSTOMER.FORENAME, CUSTOMER.SURENAME, ORDERS.ORDERDATE FROM CUSTOMER INNER JOIN ORDERS ON CUSTOMER.CUSTOMERID = ORDER.CUSTOMERID;
SELECT ORDERS.DELIVERYID, DELIVERY.DELIVERYID, DELIVERY.MAXWEIGHT, DELIVERY.MAXSIZE FROM ORDERS RIGHT JOIN DELIVERY ON ORDERS.DELIVERYID = DELIVERY.DELIVERYID;