CREATE TABLE CUSTOMER ( 
    CUSTOMERID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COMPANY VARCHAR(100) NOT NULL,
    FORENAME VARCHAR(100), 
    SURNAME VARCHAR(100), 
    ADDRESS VARCHAR(100) NOT NULL);

CREATE TABLE STORAGES ( 
    STORAGELOCATION INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CAPACITY INT NOT NULL,
    PRODUCTNAME VARCHAR(100));

CREATE TABLE DELIVERY ( 
    MAXWEIGHT INT NOT NULL,
    DELIVERY_DATE DATE NOT NULL, 
    DELIVERY_ADDRESS VARCHAR(100) NOT NULL,
    DELIVERYID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CUSTOMERID INT NOT NULL,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER (CUSTOMERID));

CREATE TABLE PRODUCT ( 
  	PRODUCTID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    PRODUCTNAME VARCHAR(100) NOT NULL,
    PRICE INT NOT NULL, 
    SIZE INT NOT NULL,
    WEIGHT INT NOT NULL,
  	STORAGELOCATION INT,
    FOREIGN KEY (STORAGELOCATION) REFERENCES STORAGES (STORAGELOCATION));

CREATE TABLE ORDERS ( 
    ORDERDATE DATE NOT NULL,
    ORDERID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  	DELIVERYID INT,
  	CUSTOMERID INT,
    FOREIGN KEY (DELIVERYID) REFERENCES DELIVERY (DELIVERYID),
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER (CUSTOMERID));


CREATE TABLE ORDERPRODUCT(
    ORDERPRODUCT BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUCTCOUNT INT,
    PRODUCTID INT,
    ORDERID INT,
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT (PRODUCTID),
    FOREIGN KEY (ORDERID) REFERENCES ORDERS (ORDERID));

INSERT INTO CUSTOMER (COMPANY, FORENAME, SURNAME, ADDRESS) VALUES ('RyoUkot', 'Petteri', 'Kivi', 'Kuja 2');
INSERT INTO CUSTOMER (COMPANY, FORENAME, SURNAME, ADDRESS) VALUES ('RyoUkot', 'Pete', 'Oja', 'Kuja 3');
INSERT INTO CUSTOMER (COMPANY, FORENAME, SURNAME, ADDRESS) VALUES ('Ryoäijät', 'Topi', 'Saha', 'Tie 15');
INSERT INTO DELIVERY (MAXWEIGHT, DELIVERY_DATE, DELIVERY_ADDRESS, CUSTOMERID) VALUES (100, '2020-06-14' , 'Kotikuja 13, 65200 VAASA', 1);
INSERT INTO DELIVERY (MAXWEIGHT, DELIVERY_DATE, DELIVERY_ADDRESS, CUSTOMERID) VALUES (100, '2020-06-16' , 'Kotikuja 54, 65200 VAASA', 1);
INSERT INTO DELIVERY (MAXWEIGHT, DELIVERY_DATE, DELIVERY_ADDRESS, CUSTOMERID) VALUES (150, '2020-02-16' , 'Kotikuja 535, 54533 SEINAJOKI', 1);
INSERT INTO ORDERS (ORDERDATE) VALUES ('2020-04-14');
INSERT INTO ORDERS (ORDERDATE) VALUES ('2020-04-12');
INSERT INTO STORAGES (CAPACITY, PRODUCTNAME) VALUES (5, 'Tuoli');
INSERT INTO STORAGES (CAPACITY, PRODUCTNAME) VALUES (5, 'Kiikku');
INSERT INTO STORAGES (CAPACITY, PRODUCTNAME) VALUES (5, 'Sänky');
INSERT INTO STORAGES (CAPACITY, PRODUCTNAME) VALUES (5, 'Sohva');
INSERT INTO PRODUCT (PRODUCTNAME, PRICE, SIZE, WEIGHT, STORAGELOCATION) VALUES ('Sohva', 900, 80, 1, 4);
INSERT INTO PRODUCT (PRODUCTNAME, PRICE, SIZE, WEIGHT, STORAGELOCATION) VALUES ('Sänky', 800, 90, 2, 3);
INSERT INTO PRODUCT (PRODUCTNAME, PRICE, SIZE, WEIGHT, STORAGELOCATION) VALUES ('Tuoli', 450, 90, 2, 1); 
INSERT INTO PRODUCT (PRODUCTNAME, PRICE, SIZE, WEIGHT, STORAGELOCATION) VALUES ('Kiikku', 620, 90, 2, 2);
INSERT INTO PRODUCT (PRODUCTNAME, PRICE, SIZE, WEIGHT) VALUES ('Jakkara', 50, 90, 2);
INSERT INTO ORDERPRODUCT (PRODUCTCOUNT, PRODUCTID, ORDERID) VALUES (2, 1, 1);
INSERT INTO ORDERPRODUCT (PRODUCTCOUNT, PRODUCTID, ORDERID) VALUES (1, 2, 1);
INSERT INTO ORDERPRODUCT (PRODUCTCOUNT, PRODUCTID, ORDERID) VALUES (4, 3, 1);
INSERT INTO ORDERPRODUCT (PRODUCTCOUNT, PRODUCTID, ORDERID) VALUES (1, 4, 2);
INSERT INTO ORDERPRODUCT (PRODUCTCOUNT, PRODUCTID, ORDERID) VALUES (1, 2, 2);
UPDATE ORDERS SET DELIVERYID = 2 WHERE ORDERID = 1;
UPDATE ORDERS SET DELIVERYID = 1 WHERE ORDERID = 2;
UPDATE ORDERS SET CUSTOMERID = 1 WHERE ORDERID = 1;
UPDATE ORDERS SET CUSTOMERID = 2 WHERE ORDERID = 2;
UPDATE DELIVERY SET CUSTOMERID = 2 WHERE DELIVERYID = 1;
UPDATE DELIVERY SET CUSTOMERID = 1 WHERE DELIVERYID = 2;
INSERT INTO ORDERS (ORDERDATE, DELIVERYID, CUSTOMERID) VALUES ('2020-04-14', NULL, 2);
INSERT INTO ORDERS (ORDERDATE, DELIVERYID, CUSTOMERID) VALUES ('2020-05-17', NULL, 3);
INSERT INTO ORDERS (ORDERDATE, DELIVERYID, CUSTOMERID) VALUES ('2012-02-21', NULL, 2);
INSERT INTO ORDERS (ORDERDATE, DELIVERYID, CUSTOMERID) VALUES ('2014-12-30', NULL, 1);
INSERT INTO ORDERS (ORDERDATE, DELIVERYID, CUSTOMERID) VALUES ('2015-07-24', NULL, 1);