-- UPDATE table_name
-- SET column1 = value1, column2 = value2, ...
-- WHERE condition;

-- DELETE FROM table_name WHERE condition;

UPDATE ORDERS SET ORDERDATE = '2020-03-12' WHERE ORDERID = 1;
UPDATE CUSTOMER SET COMPANY = "terve.fi" WHERE COMPANY = "RyoUkot";
UPDATE PRODUCT SET WEIGHT = 15 WHERE PRODUCTID = 1;
DELETE FROM CUSTOMER WHERE FORENAME = "Petteri";
DELETE FROM PRODUCT WHERE PRODUCTID = 1;
DELETE FROM ORDERS WHERE ORDERID = 1;